"""add parser_version to edi_files

Revision ID: 0a97a228d6d4
Revises: cbd440d2913d
Create Date: 2026-05-18 15:17:18.444542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a97a228d6d4'
down_revision: Union[str, None] = 'cbd440d2913d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('edi_files', sa.Column('parser_version', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('edi_files', 'parser_version')
    # ### end Alembic commands ###
