"""add_previous_payer_claim_control_no_to_claims

Revision ID: 39ffd8d119de
Revises: 0a97a228d6d4
Create Date: 2026-05-18 16:32:07.894275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39ffd8d119de'
down_revision: Union[str, None] = '0a97a228d6d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claims', sa.Column('previous_payer_claim_control_no', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('claims', 'previous_payer_claim_control_no')
    # ### end Alembic commands ###
