"""add_claim_lifecycles_table

Revision ID: 50f3d014f213
Revises: f236733d715a
Create Date: 2026-05-19 11:32:47.338928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50f3d014f213'
down_revision: Union[str, None] = 'f236733d715a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim_lifecycles',
    sa.Column('original_claim_id', sa.BigInteger(), nullable=False),
    sa.Column('parent_claim_id', sa.BigInteger(), nullable=False),
    sa.Column('child_claim_id', sa.BigInteger(), nullable=False),
    sa.Column('relationship_type', sa.Enum('corrected', 'replacement', 'resubmission', 'void', name='relationshiptype'), nullable=False),
    sa.Column('iteration_number', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['child_claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['original_claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['parent_claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_lifecycles_child_claim_id'), 'claim_lifecycles', ['child_claim_id'], unique=False)
    op.create_index('ix_claim_lifecycles_original_child', 'claim_lifecycles', ['original_claim_id', 'child_claim_id'], unique=True)
    op.create_index(op.f('ix_claim_lifecycles_original_claim_id'), 'claim_lifecycles', ['original_claim_id'], unique=False)
    op.create_index(op.f('ix_claim_lifecycles_parent_claim_id'), 'claim_lifecycles', ['parent_claim_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claim_lifecycles_parent_claim_id'), table_name='claim_lifecycles')
    op.drop_index(op.f('ix_claim_lifecycles_original_claim_id'), table_name='claim_lifecycles')
    op.drop_index('ix_claim_lifecycles_original_child', table_name='claim_lifecycles')
    op.drop_index(op.f('ix_claim_lifecycles_child_claim_id'), table_name='claim_lifecycles')
    op.drop_table('claim_lifecycles')
    # ### end Alembic commands ###
