"""Add content_hash to edi_files

Revision ID: f236733d715a
Revises: 39ffd8d119de
Create Date: 2026-05-18 23:12:40.384668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f236733d715a'
down_revision: Union[str, None] = '39ffd8d119de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('edi_files', sa.Column('content_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_edi_files_content_hash'), 'edi_files', ['content_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_edi_files_content_hash'), table_name='edi_files')
    op.drop_column('edi_files', 'content_hash')
    # ### end Alembic commands ###
